### ISSUE TITLE
This is not compatible with Joystick?

### ISSUE THREAD

**Issue by jeancallisti** [linuxgurugamer/Through-The-Eyes#2]
I'm trying to use this with VR and I don't understand what's the general philosophy.

- If you're wearing the VR headset then you cannot use WASD and IJKLHN because you can't see the keyboard.
- So then I thought I might want to use a joystick, at least as a substitute to IJKLHN. But it doesn't seem to do anything. (I'm using the joystick to fly the rocket with no issues).

Am I missing something?

EDIT: yes, I was missing something : this mod is not fully compatible with the Vivero mod. However when not in VR, first-person EVA works a expected and the joystick can be used.

**Comment by jeancallisti** [comment]
Also the camera does not follow the Kerbal's body when he moves. So as soon as he moves you end up watching the Kerbal drift away from the camera...

**Comment by linuxgurugamer** [comment]
Re. the VR, no idea about it, it wasn't written for VR to begin with.

**Comment by jeancallisti** [comment]
Ok sorry it didn't occur to me that this mod and the VR mod were developed each entirely separately, see my last post on the forums: if there was a way to make them work together by fixing the camera positioning issues it would be awesome: first-person EVA in VR is the last thing missing to get the ultimate immersion in KSP all-IVA missions.

**Comment by linuxgurugamer** [comment]
As discussed on the forums, it's up to the VR guy, if he contacts me, I'll work with him, but not having any VR gear or any interest in it, it's rather hard for me to do anything
