### ISSUE TITLE
Flickering textures while on surface, not in space.

### ISSUE THREAD

**Issue by Alexsys** [linuxgurugamer/Through-The-Eyes#3]
https://youtu.be/iN-VspHgD2c
[KSP.log](https://github.com/linuxgurugamer/Through-The-Eyes/files/8582047/KSP.log)

Sup!
The textures tend to flicker as the kerbal walks on a surface, yet in space when we float EVA its all well, no flickering :)

**Comment by linuxgurugamer** [comment]
Please try to reproduce this with a minimal set of mods, you have too many installed for me to deal with.  Once you can isolate which mod interactions may be causing the issue, I might be able to take a look

**Comment by JonnyOThan** [comment]
I’m pretty sure this is a consequence of pulling the near clip distance in without touching the far clip.

**Comment by JonnyOThan** [comment]
Current behavior: 
![current](https://user-images.githubusercontent.com/9804078/175828258-bd02c509-7b67-422c-a8c1-37018d348617.png)

Reducing far plane to keep the same near/far ratio:
![closerFarPlane](https://user-images.githubusercontent.com/9804078/175828260-759dde06-3bb1-4182-8dfe-c42130e58a70.png)

Notice how the sun light is not properly being shadowed by the rim of the crater in the "current" image.
